crawler: gspread2 # gspread or xlsx
SHEET_DATA:
  Caceres:
    DEMAND_COLUMN_RANGE:
    - J
    - O
    DEMAND_HEADERS_MAP:
      "Organización": usuario
    DEMAND_INITIAL_ROW: 4
    DEMAND_IGNORED_COLUMNS:
      - 3
    DEMAND_COLUMN_TYPES:
      - str
      - int
      - int
      - str
      - str
      - str
    STOCK_COLUMN_RANGE:
    - B
    - H
    STOCK_HEADERS_MAP:
      Usuario Telegram: usuario
    STOCK_INITIAL_ROW: 4
    STOCK_IGNORED_COLUMNS:
      - 4
    STOCK_COLUMN_TYPES:
      - str
      - int
      - int
      - int
      - str
      - str
      - str

SPREAD_SHEET_URL: "https://docs.google.com/spreadsheets/d/13kPmM2GXyzMb9H2C1dikm1qg4n6ehD6309uK3wPhrJc/edit#gid=1873691210"

SOCKETIO_PORT: 8000


SCOPES: # If modifying these scopes, delete the file token.pickle
  - 'https://www.googleapis.com/auth/spreadsheets.readonly'
...
